[server]
hostname = "localhost"
offset = 1
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"

[database.identity_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_DB?autoReconnect=true&amp;allowPublicKeyRetrieval=true&amp;useSSL=false"
username = "wso2carbon"
password = "wso2carbon"
driver = "com.mysql.cj.jdbc.Driver"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://mysql:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;allowPublicKeyRetrieval=true&amp;useSSL=false"
username = "wso2carbon"	
password = "wso2carbon"	
driver = "com.mysql.cj.jdbc.Driver"

[keystore]
userstore_password_encryption = "InternalKeyStore"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

# The KeyStore which is used for encrypting/decrypting internal data. By default the primary keystore is used as the internal keystore.

#[keystore.internal]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

# The KeyStore which is used for tls communication. By default the primary keystore is used as the tls keystore.

#[keystore.tls]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

#Google reCAPTCHA settings.

#[recaptcha]
#enabled = true
#api_url = "https://www.google.com/recaptcha/api.js"
#verify_url = "https://www.google.com/recaptcha/api/siteverify"
#site_key = ""
#secret_key = ""

# SMTP email sender settings.
#[output_adapter.email]
#from_address= "abcd@gmail.com"
#username= "abcd"
#password= "xxxx"
#hostname= "smtp.gmail.com"
#port= 587

[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1

[event_listener.properties]
notification_endpoint = "https://api-manager:9443/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "WSO2-IS"

[event.default_listener.validation]
priority = 10
enable = true

[event.default_listener.workflow]
priority = 100
enable = false

[event.default_listener.identity_mgt]
priority = 50
enable = true

[event.default_listener.scim]
priority = 90
enable = false

[event.default_listener.scim_tenant_mgt]
priority = 90
enable = false

[event.default_listener.scim2]
priority = 93
enable = true

[event.default_listener.scim2_tenant_mgt]
priority = 93
enable = true

[event.default_listener.governance_identity_mgt]
priority = 95
enable = true

[event.default_listener.governance_identity_store]
priority = 97
enable = true
data_store = "org.wso2.carbon.identity.governance.store.JDBCIdentityDataStore"
enable_hybrid_data_store = false

[event.default_listener.application_authentication]
priority = 11
enable = false

[event.default_listener.oauth_listener]
priority = 11
enable = true

[event.default_listener.mutual_tls_authenticator]
priority = 501
enable = true

[event.default_listener.basic_auth_client_authenticator]
priority = 5
enable = true

[event.default_listener.user_deletion]
priority = 98
enable = true

[event.default_listener.consent_mgt_handler]
priority = 100
enable = true

[event.default_listener.user_session_termination]
priority = 98
enable = true

[event.default_listener.jit_provisioning_handler]
priority = 100
enable = true

[event.default_listener.post_auth_association_handler]
priority = 10
enable = true

[event.default_listener.subject_identifier_handler]
priority = 100
enable = true

[event.default_listener.failed_lockout_count_handler]
priority = 100
enable = true

[event.default_listener.username_resolver]
priority = 4
enable = true

[event.default_listener.userid_resolver]
priority = 5
enable = true

[event.default_listener.user_mgt_audit_logger]
priority = 9
enable = true

[event.default_listener.user_management_audit_logger]
priority = 14
enable = true

[event.default_listener.user_failure_audit_logger]
priority = 12
enable = true

[event.default_listener.unique_claim_user_operation_event_listener]
priority = 20
enable = false

[event.default_listener.user_claim_audit_logger]
priority = 9
enable = true
LogUpdatedClaimsOnly = true

[event.default_listener.client_certificate_authentication_handler]
priority = 250
enable = true

[event.default_listener.is_introspection_data_provider]
priority = 503
enable = true

[event.default_listener.outbound_provisioning_error_handler]
priority = 20
enable = true

[[resource.access_control]]
context = "(.)/keymanager-operations/user-info/claims(.)"
secure = true
http_method = "GET"
permissions = "/permission/admin/manage/identity/usermgt/list"
scopes = "internal_user_mgt_list"

[[resource.access_control]]
context = "(.*)/keymanager-operations/user-info/claims/generate"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/usermgt/list"
scopes = "internal_user_mgt_list"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/create"
scopes = "internal_application_mgt_create"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "GET"
permissions = "/permission/admin/manage/identity/applicationmgt/view"
scopes = "internal_application_mgt_view"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "DELETE"
permissions = "/permission/admin/manage/identity/applicationmgt/delete"
scopes = "internal_application_mgt_delete"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "PUT"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

[[resource.access_control]]
context = "(.*)/keymanager-operations/dcr/register(.*)"
secure = true
http_method = "POST"
permissions = "/permission/admin/manage/identity/applicationmgt/update"
scopes = "internal_application_mgt_update"

[tenant_context.rewrite]
custom_webapps = ["/keymanager-operations/"]

[system.parameter]
"org.wso2.CipherTransformation" = "RSA/ECB/OAEPwithSHA1andMGF1Padding"

[encryption]
internal_crypto_provider = "org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider"

[identity_mgt]
data_store.class_name = "org.wso2.carbon.identity.governance.store.JDBCIdentityDataStore"

[identity_mgt.notification]
resolve_notification_channel = true
default_locale = "en_US"

[identity_mgt.user_onboarding]
enable_email_verification = false
verification_email_validity = 1440
lock_on_creation = true
ask_password_email_validity = 1440
ask_password_account_activation = true
password_generator = "org.wso2.carbon.user.mgt.common.DefaultPasswordGenerator"
disable_random_value_for_credentials = false

[identity_mgt.user_onboarding.notification]
manage_internally = true

[identity_mgt.tenant_registration]
ask_password_email_validity = 1440

[identity_mgt.user_self_registration]
allow_self_registration = true
enable_account_lock_for_verified_preferred_channel = false
enable_detailed_api_response = false

[saml]
response.validity = 5
enable_user_domain_crpto = false
signing_alg = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
digest_alg = "http://www.w3.org/2001/04/xmlenc#sha256"
assertion_encryption_alg = "http://www.w3.org/2001/04/xmlenc#aes256-cbc"
key_encryption_alg = "http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p"
artifact.validity = 4
metadata.validity_period = 60
metadata.enable_signing = false
enable_request_validity_period = false
slo.host_name_verification = true

[saml.endpoints]
ecp = "${carbon.protocol}://${carbon.host}:${carbon.management.port}/samlecp"

[saml.extensions]
assertion_builder = "org.wso2.carbon.identity.sso.saml.builders.assertion.DefaultSAMLAssertionBuilder"
encrypter = "org.wso2.carbon.identity.sso.saml.builders.encryption.DefaultSSOEncrypter"
signer = "org.wso2.carbon.identity.sso.saml.builders.signature.DefaultSSOSigner"
redirect_signature_validator = "org.wso2.carbon.identity.sso.saml.validators.SAML2HTTPRedirectDeflateSignatureValidator"
response_builder = "org.wso2.carbon.identity.sso.saml.builders.DefaultResponseBuilder"

[outbound_provisioning_management]
reset_provisioning_entities_on_config_update = true
use_user_tenant_domain_in_saas_apps = false

[authorization_manager.properties]
GroupAndRoleSeparationEnabled = false

[extension_manager]
enable = true
